### ISSUE TITLE
Kanban Overall Design

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#146]
Fever dreams?  Or is it a design I've written while counterintuitively congested and popping cough drops and decongestant pills like they were bacon at a buffet: ![Magic](https://dl.dropboxusercontent.com/u/16084968/Inthe.AM/intheam_kanban.JPG)

# Infrastructure

* [x] API
  * [x] #156 Add endpoint for fetching kanban board tasks (*must*, for technical reasons, not be the same endpoint used for user tasks).
  * [x] #158 Add endpoint inviting an existing user to join a kanban board.
  * [x] #159 Add endpoint authorizing the currently logged-in user with a invitation-specified kanban board.
  * [x] #160  Add endpoint removing a user from a form-specified kanban board.
* [x] Sync
  * [x] #154 **From kanban**: Add functionality for automatically creating/updating tasks in users' task lists matching now-assigned or previously-assigned tasks.
  * [x] #155 **To kanban**: Add functionality to post-sync behaviors that cause task updates to be propagated to the kanban-backed task list.
     * Sanitize column changes, and update user task list if necessary!
        * Clear invalid ``intheamkanbanboarduuid`` and ``intheamkanbantaskuuid`` fields.
        * Prevent changing to a column name that does not exist on the associated board.
        * Prevent changing to a color that is not valid.
  * [x] #161 Alter existing announcements channel to listen for Redis pubsub events indicating that a sync has taken place.
  * [x] #162 Write new management command service that will monitor synchronization operations and emit Redis pubsub messages.
* [x] UI
  * [x] #149 Add user-side configuration section showing kanban board membership, and allowing one to **remove** onesself from a connected kanban board.
  * [x] #150 Add user-side page allowing the currently logged-in user to join a kanban board via an invitation link.
  * [x] #151 Add kanban board invitation view.
  * [x] #152 Add kanban board view.
  * [x] #153 Add task edit view (modal).
* [x] Models
  * [x] #147 Add kanban board model (subclasses TaskStore)
     * Name
     * UUID (+INDEX)
     * Column Names (PDV) (Default: Backlog (implied), Ready, Doing, Done)
     * (Inherit all fields)
     * (Update TaskStore to allow null users!)
  * [x] #148 Add kanban membership model.
     * Invitation UUID (+INDEX)
     * Kanban board UUID  (+INDEX)
     * Invited User (+INDEX)
     * Sender
     * Created
     * Updated
     * Role
     * Accepted (bool)
     * Valid (bool)
* [ ] Polish
  * [x] #165: Add functionality for causing non-local Inthe.AM accounts to periodically sync.
  * [ ] #175: Update eventstream to handle Kanban boards.
  * [ ] #176: Switch from head checks to listening for pubsub events.

# Requisite UDAs

* ``intheamkanbanboarduuid``: Kanban Board UUID
* ``intheamkanbantaskuuid``: Task on Kanban Board's UUID
* ``intheamkanbancolumn``: Name of the column in which the task is currently displayed.
* ``intheamkanbancolor``: Color of the task on the kanban board.
* ``intheamkanbanassignee``: Username of the user a given task is assigned to.
* ``intheamkanbansortorder``: Sort position in the existing kanban column.

# Details

* User can be a member of any number of Kanban boards.
* User can switch to kanban board view by clicking a link in the navbar, at which point the navbar will be replaced with the kanban navigation.

**Comment by coddingtonbear** [comment]
After quite a lot of work, there was still going to be so much more before I'd be able to release a really-solid product, so I've instead bitten the bullet and -- disregarding sunk costs, I've cancelled this project and instead built solid integration with Trello.  You, dear reader, can turn it on, too, by clicking a single button in your settings.
